name: Bug report
description: Create a report to help us improve
labels: ["bug"]
body:

  - type: textarea
    id: issue
    attributes:
      label: What happened?
      description: |
        A clear and concise description of what the bug is.
        
        **NOTE**: If you have not already, please search our [issues](https://github.com/intellij-elm/intellij-elm/issues)
        and [pull request](https://github.com/intellij-elm/intellij-elm/pulls) for report of the same issue,
        and upgrade to the [latest version](https://github.com/intellij-elm/intellij-elm/releases) to confirm that the problem is not already fixed.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output or stack trace
      description: |
        Please copy and paste any relevant log output.
        Add the full stack trace if available.
        If possible, run the failing task with `--stacktrace` flag.
        
        **NOTE**: This will be automatically formatted into code, so there is no need for backticks.
      render: shell

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior – provide your build configuration.
    validations:
      required: true

  - type: textarea
    id: intellij-about
    attributes:
      label: IntelliJ IDE details (should contain the Elm plugin version and OS details)
      description: Go to `Help` -> `About` then press `Copy and Close` and paste it here
    validations:
      required: true

  - type: textarea
    id: intellij-elm-config
    attributes:
      label: Content of the Elm configuration in IntelliJ IDE settings
      description: Go to `Settings` -> `Languages & Frameworks` -> `Elm` make a screenshot of the Elm configuration details and paste it here
    validations:
      required: false
